FROM alpine
CMD ["echo", "-------------------------------------------------------------------\n\
👋 Hello from Porter!\n\
-------------------------------------------------------------------\n\
-------------------------------------------------------------------\n\
Your application is being deployed.\n\
To view build logs, navigate to your connected GitHub repo and     \n\
select the Actions tab.\n\
-------------------------------------------------------------------\n\
-------------------------------------------------------------------\n\
For more information, visit:\n\
https://docs.getporter.dev/docs/setting-up-cicd-1\n\
-------------------------------------------------------------------"]