# All build artifacts are built in github actions, and copied in
FROM ubuntu as runner
WORKDIR /porter
COPY bin/app /porter/
COPY bin/migrate /porter/
COPY build/ /porter/static
RUN chmod +x /porter/app /porter/migrate