// These locations are the regions where the default system and monitoring sku types are available (last checked 12/19/2023)
export const AzureLocationOptions = [
  { value: "australiaeast", label: "Australia East" },
  { value: "brazilsouth", label: "Brazil South" },
  { value: "canadacentral", label: "Canada Central" },
  { value: "centralindia", label: "Central India" },
  { value: "centralus", label: "Central US" },
  { value: "eastasia", label: "East Asia" },
  { value: "eastus", label: "East US" },
  { value: "eastus2", label: "East US 2" },
  { value: "francecentral", label: "France Central" },
  { value: "northeurope", label: "North Europe" },
  { value: "norwayeast", label: "Norway East" },
  { value: "southafricanorth", label: "South Africa North" },
  { value: "southcentralus", label: "South Central US" },
  { value: "swedencentral", label: "Sweden Central" },
  { value: "switzerlandnorth", label: "Switzerland North" },
  { value: "uaenorth", label: "UAE North" },
  { value: "uksouth", label: "UK South" },
  { value: "westeurope", label: "West Europe" },
  { value: "westus2", label: "West US 2" },
  { value: "westus3", label: "West US 3" },
];

export type MachineTypeOption = {
  value: string;
  label: string;
  supportedRegions: Set<string>;
};

export const azureSupportedMachineTypes = (
  region: string
): MachineTypeOption[] => {
  return AzureMachineTypeOptions.filter((option) =>
    option.supportedRegions.has(region)
  );
};

// Retrieve updated list of supported regions by running the following command: az vm list-skus --all --output table | grep <INSTANCE_TYPE> | grep 1,2,3 | grep None | awk '{print "\047" tolower($2) "\047"}' | paste -s -d, -
// last updated 12/19/2020
const AzureMachineTypeOptions: MachineTypeOption[] = [
  {
    value: "Standard_B2als_v2",
    label: "Standard_B2als_v2",
    supportedRegions: new Set<string>([
      "australiaeast",
      "brazilsouth",
      "canadacentral",
      "centralindia",
      "centralus",
      "eastasia",
      "eastus",
      "eastus2",
      "francecentral",
      "northeurope",
      "norwayeast",
      "southafricanorth",
      "southcentralus",
      "southeastasia",
      "swedencentral",
      "switzerlandnorth",
      "uaenorth",
      "uksouth",
      "westeurope",
      "westus2",
      "westus3",
    ]),
  },
  {
    value: "Standard_B2as_v2",
    label: "Standard_B2as_v2",
    supportedRegions: new Set<string>([
      "australiaeast",
      "brazilsouth",
      "canadacentral",
      "centralindia",
      "centralus",
      "eastasia",
      "eastus",
      "eastus2",
      "francecentral",
      "northeurope",
      "norwayeast",
      "southafricanorth",
      "southcentralus",
      "southeastasia",
      "swedencentral",
      "switzerlandnorth",
      "uaenorth",
      "uksouth",
      "westeurope",
      "westus2",
      "westus3",
    ]),
  },
  {
    value: "Standard_A2_v2",
    label: "Standard_A2_v2",
    supportedRegions: new Set<string>([
      "australiaeast",
      "canadacentral",
      "centralindia",
      "eastasia",
      "eastus",
      "eastus2",
      "francecentral",
      "germanywestcentral",
      "israelcentral",
      "italynorth",
      "northeurope",
      "norwayeast",
      "polandcentral",
      "southafricanorth",
      "swedencentral",
      "switzerlandnorth",
      "uaenorth",
      "uksouth",
    ]),
  },
  {
    value: "Standard_A4_v2",
    label: "Standard_A4_v2",
    supportedRegions: new Set<string>([
      "australiaeast",
      "canadacentral",
      "centralindia",
      "eastasia",
      "eastus",
      "eastus2",
      "francecentral",
      "germanywestcentral",
      "israelcentral",
      "italynorth",
      "northeurope",
      "norwayeast",
      "polandcentral",
      "southafricanorth",
      "swedencentral",
      "switzerlandnorth",
      "uaenorth",
      "uksouth",
    ]),
  },
  {
    value: "Standard_DS1_v2",
    label: "Standard_DS1_v2",
    supportedRegions: new Set<string>([
      "australiaeast",
      "canadacentral",
      "centralindia",
      "eastasia",
      "eastus",
      "eastus2",
      "francecentral",
      "germanywestcentral",
      "israelcentral",
      "italynorth",
      "northeurope",
      "norwayeast",
      "polandcentral",
      "southafricanorth",
      "swedencentral",
      "switzerlandnorth",
      "uaenorth",
      "uksouth",
    ]),
  },
  {
    value: "Standard_DS2_v2",
    label: "Standard_DS2_v2",
    supportedRegions: new Set<string>([
      "australiaeast",
      "canadacentral",
      "centralindia",
      "eastasia",
      "eastus",
      "eastus2",
      "francecentral",
      "germanywestcentral",
      "israelcentral",
      "italynorth",
      "northeurope",
      "norwayeast",
      "polandcentral",
      "southafricanorth",
      "swedencentral",
      "switzerlandnorth",
      "uaenorth",
      "uksouth",
      "eastus2euap",
      "israelcentral",
      "italynorth",
      "polandcentral",
      "qatarcentral",
      "swedencentral",
      "switzerlandnorth",
      "westus3",
    ]),
  },
  {
    value: "Standard_D2ads_v5",
    label: "Standard_D2ads_v5",
    supportedRegions: new Set<string>([
      "australiaeast",
      "canadacentral",
      "centralindia",
      "eastasia",
      "eastus",
      "koreacentral",
      "northeurope",
      "norwayeast",
      "southafricanorth",
      "swedencentral",
      "uaenorth",
      "uksouth",
      "westus3",
    ]),
  },
  {
    value: "Standard_B4als_v2",
    label: "Standard_B4als_v2",
    supportedRegions: new Set<string>([
      "australiaeast",
      "brazilsouth",
      "canadacentral",
      "centralindia",
      "centralus",
      "eastasia",
      "eastus",
      "eastus2",
      "francecentral",
      "northeurope",
      "norwayeast",
      "southafricanorth",
      "southcentralus",
      "southeastasia",
      "swedencentral",
      "switzerlandnorth",
      "uaenorth",
      "uksouth",
      "westeurope",
      "westus2",
      "westus3",
    ]),
  },
];
