import { Event } from "./EventsTab";

export default [
  {
    id: 1,
    resource_type: "pod",
    name: "pod-test-2",
    owner_type: "deployment",
    owner_name: "pod-test",
    event_type: "critical",
    namespace: "default",
    message: "Pod crashed",
    reason: "OOM killed",
    timestamp: "2021-06-30T21:48:23Z",
    project_id: 1,
    cluster_id: 1,
    data: ["log data 1", "log data 2"],
  },
  {
    id: 2,
    resource_type: "pod",
    name: "pod-test-2",
    owner_type: "deployment",
    owner_name: "pod-test",
    event_type: "normal",
    namespace: "default",
    message: "Pod crashed",
    reason: "OOM killed",
    timestamp: "2021-06-30T21:48:23Z",
    data: ["log data 1", "log data 2"],
    project_id: 1,
    cluster_id: 1,
  },
  {
    id: 3,
    resource_type: "pod",
    name: "pod-test-2",
    owner_type: "deployment",
    owner_name: "pod-test",
    event_type: "critical",
    namespace: "default",
    message: "Pod crashed",
    reason: "OOM killed",
    timestamp: "2021-06-30T21:48:23Z",
    data: ["log data 1", "log data 2"],
    project_id: 1,
    cluster_id: 1,
  },
  {
    id: 4,
    resource_type: "pod",
    name: "pod-test-2",
    owner_type: "deployment",
    owner_name: "pod-test",
    event_type: "critical",
    namespace: "default",
    message: "Pod crashed",
    reason: "OOM killed",
    timestamp: "2021-06-30T21:48:23Z",
    data: ["log data 1", "log data 2"],
    project_id: 1,
    cluster_id: 1,
  },
] as Event[];
