"on":
  push:
    branches:
    - master
name: Deploy to porter-double
jobs:
  build-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: build-go
        uses: ./.github/actions/build-go

  build-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: build-npm
        uses: ./.github/actions/build-npm
  porter-deploy:
      runs-on: ubuntu-latest
      needs: [build-go, build-npm]
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: porter-deploy
          timeout-minutes: 30
          uses: ./.github/actions/porter-deploy
          with:
            app: porter-double
            cluster: "9"
            host: https://dashboard.internal-tools.porter.run
            project: "5"
            token: ${{ secrets.PORTER_STACK_5_9 }}
